service: nodejs-python

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws

plugins:
  - serverless-offline

functions:
  hello:
    runtime: python3.8
    handler: app/hello/run.hello
    events:
      - http: GET hello
  world:
    runtime: nodejs12.x
    handler: app/world/handler.world
    events:
      - http: GET world